export function getSampleData() {
  return [
    {
      name: '김영순',
      benefitChanged: false, planRewrittenAfterChange: false,
      totalMin: 180,
      physicalMin: 60,
      cognitiveMin: 40,
      cognitiveManageMin: 0,
      emotionalMin: 20,
      houseworkMin: 50,
      rfidStart: '09:00',
      billingStart: '09:00',
      rfidEnd: '12:00',
      billingEnd: '12:00',
      billedDays: 22,
      workDays: 22,
      insuranceGap: false,
      hasLicense: true,
      isRegistered: true,
      lastAssessmentDate: '2025-03-10',
      assessmentDoneThisYear: true,
      planSigned: true,
      planSignExempted: false,
      missingSignatures: 0,
      signatureReasonWritten: true,
      isCognitive: false,
      cognitiveNoteWritten: true,
      hasDeteriorated: false,
      actionAfterDeterioration: true,
      totalRecipients: 20,
      socialWorkerVisited: true,
      riskAssessmentDone: true,
      outcomeEvalDone: true,
      planRewrite30d: true,
    },
    {
      name: '박순자',
      benefitChanged: true, planRewrittenAfterChange: false,
      totalMin: 240,
      physicalMin: 90,
      cognitiveMin: 50,
      cognitiveManageMin: 0,
      emotionalMin: 30,
      houseworkMin: 60,
      rfidStart: '08:30',
      billingStart: '08:00',
      rfidEnd: '12:30',
      billingEnd: '13:00',
      billedDays: 25,
      workDays: 20,
      insuranceGap: false,
      hasLicense: true,
      isRegistered: true,
      lastAssessmentDate: '2026-01-15',
      assessmentDoneThisYear: true,
      planSigned: false,
      planSignExempted: false,
      missingSignatures: 3,
      signatureReasonWritten: false,
      isCognitive: false,
      cognitiveNoteWritten: true,
      hasDeteriorated: true,
      actionAfterDeterioration: false,
      totalRecipients: 20,
      socialWorkerVisited: true,
      riskAssessmentDone: true,
      outcomeEvalDone: true,
      planRewrite30d: true,
    },
    {
      name: '이정호',
      benefitChanged: false, planRewrittenAfterChange: false,
      totalMin: 150,
      physicalMin: 50,
      cognitiveMin: 30,
      cognitiveManageMin: 10,
      emotionalMin: 20,
      houseworkMin: 40,
      rfidStart: '10:00',
      billingStart: '10:00',
      rfidEnd: '12:30',
      billingEnd: '12:30',
      billedDays: 18,
      workDays: 20,
      insuranceGap: true,
      hasLicense: true,
      isRegistered: true,
      lastAssessmentDate: '2026-05-20',
      assessmentDoneThisYear: true,
      planSigned: true,
      planSignExempted: false,
      missingSignatures: 0,
      signatureReasonWritten: true,
      isCognitive: true,
      cognitiveNoteWritten: false,
      hasDeteriorated: false,
      actionAfterDeterioration: true,
      totalRecipients: 20,
      socialWorkerVisited: false,
      riskAssessmentDone: false,
      outcomeEvalDone: true,
      planRewrite30d: true,
    },
    {
      name: '최미경',
      benefitChanged: false, planRewrittenAfterChange: false,
      totalMin: 120,
      physicalMin: 40,
      cognitiveMin: 0,
      cognitiveManageMin: 0,
      emotionalMin: 20,
      houseworkMin: 60,
      rfidStart: '14:00',
      billingStart: '14:00',
      rfidEnd: '16:00',
      billingEnd: '16:00',
      billedDays: 15,
      workDays: 15,
      insuranceGap: false,
      hasLicense: true,
      isRegistered: true,
      lastAssessmentDate: '2026-04-01',
      assessmentDoneThisYear: true,
      planSigned: true,
      planSignExempted: false,
      missingSignatures: 2,
      signatureReasonWritten: false,
      isCognitive: false,
      cognitiveNoteWritten: true,
      hasDeteriorated: false,
      actionAfterDeterioration: true,
      totalRecipients: 20,
      socialWorkerVisited: true,
      riskAssessmentDone: true,
      outcomeEvalDone: false,
      planRewrite30d: true,
    },
    {
      name: '정대철',
      benefitChanged: false, planRewrittenAfterChange: false,
      totalMin: 200,
      physicalMin: 60,
      cognitiveMin: 40,
      cognitiveManageMin: 20,
      emotionalMin: 30,
      houseworkMin: 50,
      rfidStart: '09:00',
      billingStart: '09:00',
      rfidEnd: '12:20',
      billingEnd: '12:20',
      billedDays: 20,
      workDays: 22,
      insuranceGap: false,
      hasLicense: false,
      isRegistered: false,
      lastAssessmentDate: '2026-06-01',
      assessmentDoneThisYear: true,
      planSigned: true,
      planSignExempted: false,
      missingSignatures: 0,
      signatureReasonWritten: true,
      isCognitive: true,
      cognitiveNoteWritten: true,
      hasDeteriorated: true,
      actionAfterDeterioration: true,
      totalRecipients: 20,
      socialWorkerVisited: true,
      riskAssessmentDone: true,
      outcomeEvalDone: true,
      planRewrite30d: true,
    },
  ]
}
